"""sshwarden-sync — replaces bw-ssh-pubsync.

Reads SSH key items from Bitwarden (custom fields preferred, name fallback),
writes ~/.ssh/sshwarden/<alias>__<user>.pub and regenerates sshwarden.auto.conf.
"""

from __future__ import annotations

import difflib
import sys
from pathlib import Path
from typing import Generator

from sshwarden.bitwarden import SSHKeyItem, bw_sync, get_session, is_unlocked, list_ssh_items

BW_PUB_DIR = Path.home() / ".ssh" / "sshwarden"
AUTO_CONF = Path.home() / ".ssh" / "config.d" / "sshwarden.auto.conf"
LOCAL_CONF = Path.home() / ".ssh" / "config.d" / "sshwarden-local.conf"


def _sanitize(s: str) -> str:
    import re
    return re.sub(r"[^A-Za-z0-9._:-]+", "_", s)


def _pub_path(item: SSHKeyItem) -> Path:
    return BW_PUB_DIR / item.pub_filename


def _stanza(item: SSHKeyItem, pub_path: Path) -> str:
    lines = [f"Host {_sanitize(item.host_alias)}"]
    if item.hostname:
        lines.append(f"  HostName {item.hostname}")
    else:
        lines.append("  HostName <replace.me>")
    if item.user:
        lines.append(f"  User {item.user}")
    lines.append(f"  Port {item.port or '22'}")
    lines.append(f"  IdentityFile {pub_path}")
    lines.append("  IdentitiesOnly yes")
    lines.append("")
    return "\n".join(lines)


def run_sync(session: str, *, clean: bool = False) -> Generator[str, None, None]:
    """Yield log lines. Call from CLI or web UI."""
    yield "Syncing vault from server..."
    bw_sync(session)
    yield "Fetching items from Bitwarden..."
    items = list_ssh_items(session)
    ssh_items = [i for i in items if i.alias]

    if not ssh_items:
        yield "No SSH key items found in vault."
        return

    BW_PUB_DIR.mkdir(parents=True, exist_ok=True)
    AUTO_CONF.parent.mkdir(parents=True, exist_ok=True)
    BW_PUB_DIR.chmod(0o700)

    if not LOCAL_CONF.exists():
        LOCAL_CONF.touch()
        LOCAL_CONF.chmod(0o600)

    # deduplicate host aliases when multiple items share the same alias
    alias_counts: dict[str, int] = {}
    for item in ssh_items:
        alias_counts[item.alias] = alias_counts.get(item.alias, 0) + 1

    active_paths: set[Path] = set()
    stanzas: list[str] = []
    created = updated = kept = 0

    for item in ssh_items:
        pub_path = _pub_path(item)
        active_paths.add(pub_path)
        content = item.public_key + "\n" if not item.public_key.endswith("\n") else item.public_key

        if pub_path.exists():
            old = pub_path.read_text()
            if old != content:
                diff = "".join(difflib.unified_diff(
                    old.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=str(pub_path),
                    tofile=str(pub_path),
                ))
                yield f"[UPDATED] {pub_path}\n{diff}"
                pub_path.write_text(content)
                pub_path.chmod(0o600)
                updated += 1
            else:
                kept += 1
        else:
            yield f"[CREATED] {pub_path}"
            pub_path.write_text(content)
            pub_path.chmod(0o600)
            created += 1

        stanzas.append(_stanza(item, pub_path))

    if clean:
        for f in BW_PUB_DIR.glob("*.pub"):
            if f not in active_paths:
                yield f"[CLEAN] {f}"
                f.unlink()

    auto_content = (
        f"# Auto-generated by sshwarden-sync — DO NOT EDIT.\n"
        f"# Local overrides (loaded first): {LOCAL_CONF}\n\n"
        + "\n".join(stanzas)
    )
    AUTO_CONF.write_text(auto_content)
    AUTO_CONF.chmod(0o600)

    migrated_warn = [i for i in ssh_items if not i.migrated]
    if migrated_warn:
        yield f"\n[WARN] {len(migrated_warn)} item(s) using old name convention — use the web UI to migrate them."

    yield (
        f"\nDone. Created: {created}  Updated: {updated}  Unchanged: {kept}\n"
        f"Auto conf: {AUTO_CONF}\nLocal conf: {LOCAL_CONF}"
    )


def run_clear() -> Generator[str, None, None]:
    """Remove all files in ~/.ssh/sshwarden/ and delete sshwarden.auto.conf."""
    removed = 0
    if BW_PUB_DIR.exists():
        for f in BW_PUB_DIR.glob("*.pub"):
            f.unlink()
            yield f"[REMOVED] {f}"
            removed += 1
    if AUTO_CONF.exists():
        AUTO_CONF.unlink()
        yield f"[REMOVED] {AUTO_CONF}"
    yield f"\nDone. Removed {removed} public key(s) and auto.conf."


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Sync Bitwarden SSH keys to ~/.ssh/sshwarden/")
    parser.add_argument("--clean", action="store_true", help="Remove stale .pub files")
    parser.add_argument("--session", help="bw session token (overrides stored session)")
    args = parser.parse_args()

    session = args.session or get_session()
    if not session or not is_unlocked(session):
        print("Error: Bitwarden vault is locked. Unlock via the sshwarden web interface.", file=sys.stderr)
        sys.exit(1)

    for line in run_sync(session, clean=args.clean):
        print(line)
